### ISSUE TITLE
Adição de discussões no repositório

### ISSUE THREAD

**Issue by jjpaulo2** [Universidade-Livre/ciencia-da-computacao#1]
Olá, tudo bem? Gostaria de saber se há a possibilidade de ativar as discussões do github nesse repositório, onde possamos adicionar os tópicos relacionados a áreas da computação e debater sobre eles.

**Comment by gblnovaes** [comment]
Seria uma boa ...abrir um canal para conversamos.

**Comment by Camilotk** [comment]
Estamos preparando um servidor no Discord, com vocês acham que é mais interessante de estruturar a discussão: Discord (👍) ou GitHub Discussions (😆)?

**Comment by jjpaulo2** [comment]
Poxa, muito massa a ideia do Discord. Eu super apoio! 😄 
Também acho que o Discord não exclui a possibilidade da existência de um fórum aqui.

**Comment by jjpaulo2** [comment]
Poxa, muito massa a ideia do Discord. Eu super apoio! 😄

**Comment by gblnovaes** [comment]
@Camilotk Já está disponível o server no discord ?

**Comment by Camilotk** [comment]
O @mateusrovedaa tá cuidando disso, ele tá meio off nos últimos dias por questão de saúde, mas tá trabalhando nisso quando tiver pronto ele posta o link de convite aqui e fecha a issue.

**Comment by mateusrovedaa** [comment]
Desculpa a demora galera, segue o link para entrar no Discord: https://discord.gg/wymGhmf7BT
