### ISSUE TITLE
Cursos do Veduca OFF

### ISSUE THREAD

**Issue by Camilotk** [Universidade-Livre/ciencia-da-computacao#10]
Pessoas que estavam fazendo o Curso de Metodologia da Pesquisa no Veduca me reportaram que o site ficou off e subiu como Trillio Academy (que era um projeto privado da mesma rede). Aparentemente eles moveram todos os antigos conteúdos (que já estavam a quase uma década disponíveis gratuitamente) do Veduca para a Trillio.

Os cursos de Estatística e Probabilidade (antes da USP no Veduca) e Metodologia da Pesquisa Científica (antes da USP no Veduca) vão ficar indisponíveis por uns dias até eu saber como proceder.

Talvez eu acabe revertendo para os cursos antigos que tinham antes desses, mas vou pensar um pouco na melhor solução. Caso queiram sugerir substitutos agradeço.

**Comment by Camilotk** [comment]
Eu entrei em contato com a Plataforma da Trillio, mas sem sucesso para saber como vai funcionar a migração de conteúdo. Por via das dúvidas, como não sei se os cursos permanecerão gratuitos e de livre acesso após a realocação de plataforma eles serão removidos do currículo.

Os cursos de **Estatística e Probabilidade** e **Metodologia da Pesquisa em Computação** que antes eram oferecidos na Plataforma do Veduca foram substituídos:
- **Estatística e Probabilidade** foi substituído por o [Curso de Estatística e Probabilidade da UNIVESP](https://www.youtube.com/playlist?list=PLxI8Can9yAHeeWqe3m9HZFiBhT33Mfxew)
- **Metodologia da Pesquisa em Computação** foi substituído por o [Curso de Metodologia da Pesquisa em Computação da UFF](https://www.youtube.com/playlist?list=PLclUQno6PMpQO0-XrDwWsPzRzEvjwp1__)

Essa é a solução definitiva do problema, não pretendo retornar os conteúdos para as plataformas da Trillio ou do Veduca mesmo que eventualmente os conteúdos estejam novamente disponíveis uma vez em que o suporte dos mesmos não respondeu de nenhuma forma a respeito das mudanças.

Aos alunos que estavam fazendo o Curso de **Metodologia da Pesquisa** da USP pelo Veduca e me informaram da queda da plataforma fico a disposição caso precisem de ajuda para encontrar outro Curso com certificado como o da [Fiocruz](https://campusvirtual.fiocruz.br/gestordecursos/hotsite/metodologia) que esporadicamente abrem turmas gratuitas.

Qualquer dúvida ou comentário sinta-se livre para abrir uma nova issue ou nos marcar em uma discussão no servidor da ULivre no Discord.

**Comment by Sabrina902-prog** [comment]
Ok
