### ISSUE TITLE
Sugestão para disciplina de Programação Linear

### ISSUE THREAD

**Issue by elvcastelo** [Universidade-Livre/ciencia-da-computacao#11]
O professor Manoel Campêlo da UFC possui playlists que cobrem a disciplina de Programação Linear. A disciplina é relevante para a área de Ciência da Computação dado as suas aplicações.

https://www.youtube.com/channel/UCYe-qV12CP64BewDy2-BY5A/playlists

**Comment by Camilotk** [comment]
Adicionado em [cursos extras](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/extras/courses.md).
