### ISSUE TITLE
Especialização em gestão de TI

### ISSUE THREAD

**Issue by jeanbispo** [Universidade-Livre/ciencia-da-computacao#16]
Importante abrir uma thread para sugestões de conteúdos para a formulação de um curso voltado para gestão. 

Exemplo: 

Scrum: https://www.youtube.com/watch?v=HcZVxsVZ-48&list=PLRj4UESgCLz1uwaFje483eV8hQiBguW-P&ab_channel=minutoagil

**Comment by Camilotk** [comment]
Issue fechada por inatividade a 90 dias, caso queira novamente reabri-la peço que abra uma nova issue.
