### ISSUE TITLE
Sugestão de material

### ISSUE THREAD

**Issue by lucasew** [Universidade-Livre/ciencia-da-computacao#2]
Meu professor aqui da UTFPR Santa Helena lançou o material que ele usa nas matérias dele no youtube

Atualmente tem as matérias de Estrutura de Dados, Fundamentos de Sistemas Inteligentes e Sistemas Inteligentes Aplicados

Segue link: https://www.youtube.com/c/ThiagoNaves23/playlists

**Comment by Camilotk** [comment]
Muito obrigado!
Todos os cursos vão ser adicionados no material que estamos preparando.

**Comment by lfelipemacedo** [comment]
Boa!

**Comment by kassane** [comment]
Sistemas Operacionais com Prof Carlos Maziero [UFPR]
http://wiki.inf.ufpr.br/maziero/doku.php?id=socm:start (livro + vídeos por capítulo)

Existem outros materiais que podem interessantes neste repositório. Embora o foco seja C++ existem outros materiais como referência!
https://github.com/cppbrasil/material-de-aprendizado

**Comment by lucasew** [comment]
Maziero é brabo mesmo. Prof de SO usa aqui. Dá pra seguir o mesmo fluxo.
Quase sempre o prof n passa o livro até o final pq n da tempo mas ele até
pede exercício do livro.

Esse prof tbm recomenda o Tannenbaum mas esse ele n usa tanto.

**Comment by Camilotk** [comment]
O livro + videoaulas do Prof Carlos Maziero substitui o Curso de Sistemas Operacionais da USP na grade, realmente gostei muito da didática e também de todo o empenho que ele colocou em construir esse material de qualidade. 

Alguns materiais de C++ foram adicionados a seção de Embarcados. Eu estou estudando como colocar o material do Prof Thiago Neves na seção de Data Science.

**Comment by HeiCg** [comment]
Aulas da Disciplina de Programação para Web - Icomp/Ufam
https://www.youtube.com/channel/UCAf243ssPocCpyj3iISq_Kw/videos

A disciplina no nosso currículo tem 60 horas e tem pré-requisito de Introdução a banco de dados.
Acredito que pode ser usar como overview no tópico de Desenvolvimento Web
O professor usa a documentação da w3c e do mdn para explicar a maior parte dos tópicos.
Os Tópicos são
- Html5
- Introdução a git
- Css3
- Javascript (vanilla)
- Node (direto com express)
- Resolução da atividade (jogo snake)

**Comment by Wandersonmagno** [comment]
Bom dia. Estou nos primeiros passos no mundo da programação. Aprendi muitas coisas nesse curso. Ele é bem detalhado. O curso é em inglês mas tem legendas em português. 
Espero que possa ajudar. 

https://www.edx.org/course/cs50s-web-programming-with-python-and-javascript

**Comment by Camilotk** [comment]
@Wandersonmagno boa!

Dando uma pesquisada encontrei uma versão 100% em Português produzida pela Fundação Estudar em parceria com Harvard chamado CC50. Vou estar estudando nos próximos dias como inserir isso na grade, se substituo uma matéria de introdução ou adiciono mais carga no primeiro grupo de matérias.

**Comment by Wandersonmagno** [comment]
@Camilotk.
Achei a iniciativa incrível. Obrigado.

**Comment by Camilotk** [comment]
Issue fechada. Sugestões de material agora podem ser feitas [aqui](https://github.com/Universidade-Livre/ciencia-da-computacao/issues/18)!
