### ISSUE TITLE
Curso de React não esta mais online

### ISSUE THREAD

**Issue by fejmyioqaxssyboqccfythgtaya** [Universidade-Livre/ciencia-da-computacao#22]
Curso de React não esta mais online que é listado em: 
https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/web_development.md

**Comment by Camilotk** [comment]
Esse? 

![image](https://user-images.githubusercontent.com/30880723/149425764-f232dc04-8676-4e31-a684-0a1db725f8a4.png)

**Comment by coabr** [comment]
Aparentemente voltou, lembro de checado e estava fora do ar mesmo

**Comment by Camilotk** [comment]
Muito obrigado @coabr e @fejmyioqaxssyboqccfythgtaya! Provavelmente foi porque o dono do Canal estava mexendo em alguma configuração.

Estando tudo ok, tópico fechado.
