### ISSUE TITLE
Links dando erro

### ISSUE THREAD

**Issue by bugahontas** [Universidade-Livre/ciencia-da-computacao#32]
Boa tarde! Em Especializações, na parte de Desenvolvimento Web, os links dos tópicos "HTML e CSS, Parte I", "HTML e CSS, Parte II" e "JavaScript Básico" estão dando erro de página não encontrada. Segue print desse erro, que se repete nos três links.

![Captura de tela_2022-03-28_15-50-21](https://user-images.githubusercontent.com/93399957/160467648-dcad66a4-ddaa-4190-a6f2-fd4ae546011d.png)

**Comment by LanusseMorais** [comment]
Boa tarde @bugahontas o site dos cursos sofreu atualização segue link's atualizados.
"HTML e CSS, Parte I", -> https://www.cursoemvideo.com/curso/html5-css3-modulo1/
"HTML e CSS, Parte II" -> https://www.cursoemvideo.com/curso/curso-html5-e-css3-modulo-2-de-5-40-horas/
"JavaScript Básico" -> https://www.cursoemvideo.com/curso/javascript/

**Comment by alvarorpj** [comment]
> Bom dia @alvarorpj acredito que sim, eu localizei esse curso aqui https://cursos.univesp.br/courses/3129 que acredito ser o correto, mas vou perguntar lá no discord para o pessoal.

Bom dia, sim, parece ser este mesmo. Grato

**Comment by LindonJohnson** [comment]
a maioria dos links do curso estão dando erro, estou na matéria de [Estatística e Probabilidade](https://integra.univesp.br/courses/1624) e não está pegando.

**Comment by LanusseMorais** [comment]
@LindonJohnson se puder informar os links com erro facilita que outra pessoa consiga ajudar.

**Comment by LanusseMorais** [comment]
@LindonJohnson Acredito que o link para o curso seja esse https://cursos.univesp.br/courses/1624

**Comment by LindonJohnson** [comment]
> @LindonJohnson se puder informar os links com erro facilita que outra pessoa consiga ajudar.

1 - [Estatística e Probabilidade](https://integra.univesp.br/courses/1624)
2 - [Noções de Inglês](https://integra.univesp.br/courses/3032)
3 - [Noções de Direitos Autorais, parte II](https://integra.univesp.br/courses/1936)
4 - [Cálculo I](https://integra.univesp.br/courses/1907)
5 - [Interfaces Humano-Computador](https://integra.univesp.br/courses/1603)
6- [Redes de Computadores](https://integra.univesp.br/courses/2713)
7 - [Gerência da Qualidade de Software](https://integra.univesp.br/courses/1602)

**Comment by LanusseMorais** [comment]
1 - Estatística e Probabilidade ->  https://cursos.univesp.br/courses/1624
2 - Noções de Inglês -> https://www.youtube.com/watch?v=ok5PaRPltcM&list=PLxI8Can9yAHeYb4-3dXwiY2Z9VdqhnqpM&ab_channel=UNIVESP
3 - Noções de Direitos Autorais, parte II -> :(
4 - Cálculo I -> https://www.youtube.com/playlist?list=PL2D9B691A704C6F7B
5 - Interfaces Humano-Computador -> https://www.youtube.com/playlist?list=PLxI8Can9yAHcoiFzGoyLITBKzFbiw3RIp
6- Redes de Computadores -> https://www.youtube.com/playlist?list=PLxI8Can9yAHc-_dZ6nsfoon08i2-4OvEk
7 - Gerência da Qualidade de Software -> https://www.youtube.com/playlist?list=PLxI8Can9yAHcmjsfjFdo_xJ3xhLiczzLC

@LindonJohnson o Curso "Noções de Inglês" eu não consegui achar o curso exato, mas acredito que o que informei deve subistituir bem caso encontre um melhor compartilhe please. 
Já o curso "Noções de Direitos Autorais, parte II" eu não consegui achar de jeito nenhum

**Comment by Camilotk** [comment]
Vou dar uma olhada nisso em breve, alguns desses links quebrados chegaram a ser relatados no discord e já estão corrigidos outros como Estatística e Probabilidade ainda precisam de correção, vou estar olhando todos os relatos e sugestões em breve.

Desculpem a demora.

**Comment by Camilotk** [comment]
Os links do currículo principal que estavam quebrados foram concertados, se alguém conseguir fazer o review disso para mim agradeço, mais para frente quero fazer um script que automatize esse teste.

Se puderem ajudar a testar se tá ok, agradeço.

Em breve olho as especializações.

**Comment by bugahontas** [comment]
Bom dia! Fiz o review dos links e parecem estar ok. Obrigada @Camilotk e @LanusseMorais pela atenção! :)

**Comment by mateusrovedaa** [comment]
Revisei todos os links das especializações e todos levam para os lugares definidos. Por isso, estou fechando essa issue. Caso apareçam mais links quebrados, favor abrir uma nova issue.
