### ISSUE TITLE
ubl

### ISSUE THREAD

**Issue by MarcosEchevarry** [Universidade-Livre/ciencia-da-computacao#34]

**Comment by dev-araujo** [comment]
Boa tarde gente. Não sei se caberia essa sugestão aqui. Mas, existe a possibilidade de juntarmos pessoas para fazermos outros repositórios da UBL para outros cursos? A idéia seria criarmos algo que englobasse outros cursos ligados à tecnologia e quem sabe áreas como de humanas e exatas .

**Comment by Camilotk** [comment]
@dev-araujo estamos com o currículo de Matemática a caminho.

Queremos mais cursos, mas precisamos de apoio de pessoas com formação na área e repertório para encontrar os conteúdos ajudando para lançar novos cursos, caso conheça / tenha interesse em ajudar com novos cursos chama no discord da UBL.
