### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chrisemke** [Universidade-Livre/ciencia-da-computacao#35]
Não faz mais sentido um projeto como esse estar sob uma licença mais restritiva? por exemplo a [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html)?

Um projeto como esse sob a licença MIT pode sofrer de instituições pegar o conhecimento que é/será propagado aqui, complementar e vender sem dar satisfação nenhuma para os contribuidores deste projeto

**Comment by Camilotk** [comment]
Bom, eu posso falar os motivos pelo qual o MIT foi escolhido no príncipio da UBL... e basicamente foi pela associação com o projeto do [Open Source Society University](https://github.com/ossu/computer-science) no qual serviu de modelo e inspiração em muitos níveis estruturais para o projeto que desenvolvemos.

Atualmente temos 2 licenças... a MIT e a [Unlicense](https://unlicense.org/) (que é ainda mais permissiva). Do meu ponto de vista não vejo como problema a questão de grupos privados ou outros projetos usarem nosso material como base para outros projetos (pagos ou gratuitos) o que buscamos é justamente prover o máximo de acesso possível de informações de qualidade em Português.

Acho que é OK mantermos a licença MIT (que nos permite tranquilamente relicensiar qualquer coisa futuramente em GPL caso desejarmos) até agora. 

Caso queira debater ou qualquer um queira adicionar mais algum ponto vou deixar a issue aberta, quando houver 15 dias de inatividade, fecho.
