### ISSUE TITLE
Organização de disciplinas por categorias

### ISSUE THREAD

**Issue by sswellington** [Universidade-Livre/ciencia-da-computacao#4]
Organização de disciplinas por categorias

# Formação básica
* Metodologia da pesquisa
### Matemática
Matemática elementar 
Probabilidade e Estatística
Cálculo derivada e integral 
Álgebra linear
Estrutura discretas
Cálculo numérico

### Computação
Introdução à computação
Organização de computadores
Sistemas Operacionais
Redes de Computadores
Segurança da informação
Algoritmo e complexidade
Estrutura de dados
Programação funcional
Programação Orientada Objetos
Programação paralela e distribuída
Modelagem de dados
Banco de dados
Engenharia de software
Governança de TI
Interação humano-computador

# Profissional
Desenvolvimento web
Desenvolvimento mobile
Desenvolvimento embarcado
Desenvolvimento desktop 
Ciência de dados
DevOps
QA

# Complementar
Aprendizagem de máquina 
Aprendizagem profunda
Ciência de Redes
Fundamentos de modelagem 
Introdução a Sistemas Multimídia e de Realidade Virtual
Processamento Digital de Sinais
Processamento de imagens 
Processamento de linguagem natural
Métodos de Otimização 
Modelagem de Sistemas Contínuos

## Referência 
https://www.acm.org/education/curricula-recommendations

**Comment by Camilotk** [comment]
Usei para fazer uma organização baseada no que normalmente é feito nos PPC de Cursos Superiores no Brasil, o que acha? 

![organização do currículo por área](https://i.imgur.com/DZZuqiq.png)

**Comment by sswellington** [comment]
Ficou boa a organização, seria interessante a imagem estiver disponível no figma, que permitiria a edição

Algumas disciplinas colocaria como optativa, ou criaria um linha profssional; tendo por exemplo: criação de de startups e desenvolvimento android.

Princípios de des. ágil poderia ser engenharia de software.

Não sei como funcionaria os pré-requisitos, só que teoria de grafos criaria impasse.

Recomendo a leitura da [ACM](https://www.acm.org/education/curricula-recommendations), ou mais especificamente [CS2013: Curriculum Guidelines for Undergraduate Programs in Computer Science](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf) página 40 e [CC2020: Computing Curricula 2020: Paradigms for Global Computing Education.](https://www.acm.org/binaries/content/assets/education/curricula-recommendations/cc2020.pdf) página 64

Lembrando é apenas uma sugestão e parabéns pela iniciativa.

**Comment by Camilotk** [comment]
Opa Wellington!

Primeiramente, obrigado pelas indicações das formulações e indicações da ACM vou ler sim! O arquivo original da imagem é em SVG aberto, qualquer pessoa poderá editar usando o programa de edição vetorial de sua preferência, no meu caso eu usei o Inkscape (que é Livre) para fazer.

A versão Americana deixa bem claro que optam por não incluir nenhuma matéria de formação geral, lá entendem que caso o aluno tenha interesse nesses assuntos pode buscar por conta, eu pessoalmente optei por manter o currículo completo incluindo formação geral como Escrita e Pesquisa, além de matérias Empreendedorismo e Dev. Apps. por três motivos:

        1. Não temos toda a abundância de Material em Português que é disponível comparativamente em Inglês, talvez as pessoas tivessem dificuldade de encontrar cursos sobre esses tópicos mesmo que tivessem o interesse;
        2. Acho que são importantes tal qual a formação técnica tanto para a complementação acadêmica, quanto para a atuação como Profissional, ex: Entender a Metodologia da Pesquisa é importante para que a pessoa entenda como funciona o campo científico tanto dentro da sua área (e seja capaz de consumir informações desse meio), como de todas as outras.
        3. Porque a pessoa pode não fazê-las e tudo bem, é melhor nesse caso que seja opcional a ela não fazer do que o contrário.

Os nomes eu mantive como estavam literalmente nos Cursos oferecidos com poucas adaptações (ex: Intr. a CC com Python I seria equivalente a Algoritmos).

Cara muito obrigado pela contribuição, mesmo!
Essa grade estruturada vai ser bacana para que as pessoas consigam visualizar melhor e a categorização das disciplinas ajuda na organização individual dos estudos da galera.

Como era isso mesmo eu vou dar close, qualquer questão extra que necessite pode abrir outra issue ou mandar DM no Twitter para @OCam_l.
