### ISSUE TITLE
Criação de um Main Tópic de Soft Skills

### ISSUE THREAD

**Issue by isaqueprofeta** [Universidade-Livre/ciencia-da-computacao#41]
Acredito que algumas soft skills importantes fazem falta para a maioria dos mais novos, e até mesmo mais antigos, na área. Então sugiro criar uma "matéria" ou "main topic" com materiais como os abaixo:

- Kultivi - Curso de inglês: https://kultivi.com/cursos/idiomas/ingles
- EV - Comunicação Escrita: https://www.ev.org.br/cursos/comunicacao-escrita
- EV - Oficina de Gramática: https://www.ev.org.br/cursos/oficina-de-lingua-portuguesa-gramatica
- EV - Organizacao Pessoal: https://www.ev.org.br/cursos/organizacao-pessoal
- EV - Técnicas de Redação: https://www.ev.org.br/cursos/tecnicas-de-redacao
- ENAP - Habilidades de Resolução de Problemas: https://www.escolavirtual.gov.br/curso/600

**Comment by mateusrovedaa** [comment]
Estou fechando essa issue por falta de avanços. A sugestão é válida e, se puder, abra uma PR com o tópico.
