### ISSUE TITLE
[broken link] Noções de Inglês | Univesp Integra

### ISSUE THREAD

**Issue by bpires** [Universidade-Livre/ciencia-da-computacao#45]
O curso "[Noções de Inglês](https://integra.univesp.br/courses/3032)", da seção de "Aprofundamento de Conceitos Introdutórios" encontra-se indisponível.

![image](https://user-images.githubusercontent.com/86871991/180610723-3fa6c5ca-55e7-468d-a5ff-0737e5896395.png)

Parece ser um problema da plataforma [Univesp | Integra](https://apps.univesp.br/integra/), pois o mesmo ocorre em outros cursos. 

Encontrei a uma [playlist](https://www.youtube.com/playlist?list=PLxI8Can9yAHcZW-hG1ZU9iY0-YsLVXMAW) de inglês no youtube da Univesp, porém nenhum dos conteúdos parece corresponder ao curso de "Inglês instrumental" que antes estava disponibilizado na plataforma Integra para a Engenharia da Computação.

**Comment by mateusrovedaa** [comment]
Verifiquei e a plataforma deles está com problema. Vamos aguardar mais alguns dias para ver se volta a normalidade, afinal todos os links de curso deles estão com problemas.

Fechando essa issue para mantermos a discussão na #46.

**Comment by mateusrovedaa** [comment]
@bpires esse curso é parecido? https://www.youtube.com/playlist?list=PLxI8Can9yAHcZW-hG1ZU9iY0-YsLVXMAW

**Comment by bpires** [comment]
Opa @mateusrovedaa, essa era a playlist que também tinha encontrado, mas é de outros cursos de inglês da plataforma. O previsto para a computação é o de inglês instrumental.

De toda forma, acabei de verificar e a plataforma está novamente online e o curso disponível! 🙌🏻 Com isso, consegui verificar qual o curso correspondente no You Tube.

Assim, apenas para referência futura, caso a plataforma fique offline novamente, deixo registrado que as aulas do curso estão disponíveis no You Tube sob o título "Inglês - Inglês sem mistério" 


> INGLÊS INSTRUMENTAL - ENGENHARIA DA COMPUTAÇÃO
> Disciplina: Inglês  -  Ciclo Básico - LET100
> Univesp - Universidade Virtual do Estado de São Paulo 
> Professora:Cristina Mayer Acunzo
> [- link na plataforma Univesp](https://integra.univesp.br/courses/3032)
> [- link para a playlist no YouTube](https://www.youtube.com/playlist?list=PLxI8Can9yAHeYb4-3dXwiY2Z9VdqhnqpM)
