### ISSUE TITLE
Todos os Broken Links do repositorio.

### ISSUE THREAD

**Issue by flaviomanuel** [Universidade-Livre/ciencia-da-computacao#46]
Segue os modulos que possuem os links quebrados. Acredito que todos são da Univesp.

- Estatística e Probabilidade
- Noções de Inglês
- Bancos de Dados	
- Cálculo I
- Interfaces Humano-Computador
- Redes de Computadores
- Gerência da Qualidade de Software

**Comment by mateusrovedaa** [comment]
Verifiquei e a plataforma deles está com problema. Vamos aguardar mais alguns dias para ver se volta a normalidade, afinal todos os links de curso deles estão com problemas.

Issue relacionada #45.

**Comment by mateusrovedaa** [comment]
# Cursos que encontrei no Youtube deles

- [Estatística e Probabilidade](https://www.youtube.com/watch?v=7VQE278hIXc&list=PLxI8Can9yAHeeWqe3m9HZFiBhT33Mfxew&index=1)
- **Noções de Inglês (há vários cursos de inglês no Youtube deles, ver qual é o certo)
- [Bancos de Dados](https://www.youtube.com/watch?v=pmAxIs5U1KI&list=PLxI8Can9yAHeHQr2McJ01e-ANyh3K0Lfq&index=1)
- [Cálculo I](https://www.youtube.com/watch?v=l8WMHsdNdfY&list=PLxI8Can9yAHd2Tjqa68gx_2R5YOkzOLgS&index=1)
- [Interfaces Humano-Computador](https://www.youtube.com/watch?v=5DYjVRxGy4o&list=PLxI8Can9yAHcoiFzGoyLITBKzFbiw3RIp&index=1)
- [Redes de Computadores](https://www.youtube.com/watch?v=v8vxTtT2S_0&list=PLxI8Can9yAHc-_dZ6nsfoon08i2-4OvEk)
- [Gerência da Qualidade de Software](https://www.youtube.com/watch?v=Rr89ePGLAmI&list=PLxI8Can9yAHcmjsfjFdo_xJ3xhLiczzLC&index=1)

**Comment by Camilotk** [comment]
Relacionado com a Issue https://github.com/Universidade-Livre/ciencia-da-computacao/issues/32

**Comment by mateusrovedaa** [comment]
Links voltaram a funcionar, fechando a issue por enquanto.
