### ISSUE TITLE
Certificado reconhecido pelo MEC

### ISSUE THREAD

**Issue by jonnathas** [Universidade-Livre/ciencia-da-computacao#50]
Bom dia. Gostei da iniciativa do repositório, mas gostaria de saber se estudando por ele posso pegar algum certificado reconhecido pelo MEC ou algo do tipo? 
Se ainda não for possivel, quero propor essa iniciativa também. Podemos criar umas provas online, gratuitas, e cobrar pela emição dos certificados por um valor bem mais em conta. O valor arrecadado serviria pra manter os servidores das provas no ar.

O projeto da plataforma tambem poderia ser open source.

**Comment by TonyALS** [comment]
Boa tarde @jonnathas, tudo bem?
Sobre certificados reconhecidos pelo MEC, o repositório da UBL serve mais como um agregador de conteúdo gratuito, portanto, a disponibilidade de certificados reconhecidos, se houver, estará nos cursos das próprias plataformas cujos links estão no repositório.

Já sobre sua segunda pergunta, achei a proposta de emissão de certificados uma boa ideia, mas cobrar por isso talvez não seja. Outro ponto é que os certificados não seriam reconhecidos pelo MEC, já que o credenciamento de uma instituição de ensino junto ao órgão é um processo demorado, burocrático e que talvez não agregue tanto valor.
