### ISSUE TITLE
Links quebrados

### ISSUE THREAD

**Issue by diogoodev** [Universidade-Livre/ciencia-da-computacao#51]
Bom dia pessoal, estava montando um template para acompanhar o progresso no curso e verifiquei que existem dois links quebrados na especialização > embarcados:

- Microeletronica - https://integra.univesp.br/courses/2344](https://integra.univesp.br/courses/2344
- Eletrônica Embarcada - https://integra.univesp.br/courses/2710](https://integra.univesp.br/courses/2710

**Comment by Camilotk** [comment]
Testei aqui e aparentemente estão funcionando.

![image](https://user-images.githubusercontent.com/30880723/194894317-cd821d40-a503-42d0-9389-13b5fce4acc3.png)
![image](https://user-images.githubusercontent.com/30880723/194894527-2049d2ff-66ca-4cdd-a09f-812861677873.png)

Porém, a plataforma Integra da UNIVESP passa por muitas instabilidades e esse é um problema que vamos tentar resolver. Provavelmente colocando ambos links (Youtube + Integra) em todos os cursos deles.

**Comment by mateusrovedaa** [comment]
Links funcionais, vou fechar a issue.
