### ISSUE TITLE
Planilha de acompanhamento de estudos

### ISSUE THREAD

**Issue by jonasaacampos** [Universidade-Livre/ciencia-da-computacao#52]
Olá a Todo@s

fiz uma planilha para acompanhamento e organização dos estuos.
é a mesma que estarei utilizando para organizar-me.

Caso seja interessante para o projeto, gostaria de compartilhar

Abraços!

https://docs.google.com/spreadsheets/d/1kD35Mtsx0TllMS2DzGIZ-VGkRK2bsHoTIxyK_0LiC0A/edit?usp=sharing

**Comment by alissongdev** [comment]
Muito bacana!

**Comment by robsonsan** [comment]
@jonasaacampos , uma coisa legal que pode ser inserido para incentivo é uma timeline, como na planilha da OSSU. Acho que vai ajudar muito a galera

![image](https://user-images.githubusercontent.com/38381512/206911539-2b5f05b4-3e31-4eba-9607-502a881fe569.png)

**Comment by mateusrovedaa** [comment]
Bacana a sugestão, isso ajuda quem está iniciando a saber onde parou. Eu normalmente costumo usar um markdown com checklists.
