### ISSUE TITLE
Apenas materiais produzidos em Português ou incluir materiais com legendas em Português?

### ISSUE THREAD

**Issue by Camilotk** [Universidade-Livre/ciencia-da-computacao#6]
Uma dúvida que tenho é sobre o quanto é inclusivo adicionar materiais que são legendados no material? Como vocês se sentem sobre adicionar cursos como esses:

- [Metodologia de Ciência de Dados](https://www.coursera.org/learn/data-science-methodology-pt)
- [Bancos de dados e SQL para Ciência de Dados](https://www.coursera.org/learn/sql-data-science-pt#syllabus)

É possível clicar na aula de boas-vindas e ver como funciona mesmo sem uma conta. As aulas são produzidas em Inglês mas tem toda a interface e explicações traduzidas e o conteúdo é legendado (tem que selecionar no menu de legendas e marcar "ptbr"). 

Vou deixar essa issue aberta até 15/09, usem-na para discutir porque sim ou porque não. Para motivos de simplicidade vou trabalhar com um sistema simples de votação:

- Marque um 👍 para indicar que "Por mim ok, parece tranquilo estudar com materiais legendados!"
- Marque um 👎 para indicar que "Não, prefiro que todo o conteúdo seja em Português."

Obrigado por todos os votos e opiniões, isso é importante para definir sobre como estruturar o conteúdo.

**Comment by sergjun** [comment]
👍

**Comment by Camilotk** [comment]
Para votar basta marcar o primeiro Post da issue com o emoji que representa o seu voto. Assim:

![explicação em imagem de como marcar o emoji que representa o voto no primeiro post](https://i.imgur.com/yi7UOJx.png)

Caso queiram fazer algum comentário, ou levantar alguma discussão a respeito desse tópico podem se sentir livres para adicionar uma resposta nessa issue.

**Comment by geekcom** [comment]
Acho que não deveriam manter materiais em inglês, já existem muitos repositórios neste idioma, inclusive o diferencial aqui é que seja no em português do Brasil.

**Comment by Wandersonmagno** [comment]
Tudo bem. Vou procurar material em português. Estou aqui pra contribuir da
melhor  forma possível e aprender mais e mais com todos.


Em seg., 16 de ago. de 2021 às 15:23, Daniel Rodrigues <
***@***.***> escreveu:

**Comment by Camilotk** [comment]
@geekcom eu também no geral prefiro que o conteúdo seja nativamente em Português como agora (com exceção do Curso de Aprendendo a Aprender e Pixar in a Box que são legendados) porque isso é mais acessível a todo o público que não tem domínio do inglês ao meu ver.

Ainda que preferia que todo material fosse em PT-Br, mas ao mesmo tempo seria bom poder oferecer mais conteúdo em tópicos mais difíceis de encontrar material.

Eu não sei bem qual o "certo" a proceder, seria legal mais pessoas opinando.

**Comment by mateusrovedaa** [comment]
Eu acho interessante as duas abordagens, mas do ponto de vista de acessibilidade, prefiro materiais 100% em português.
Talvez seria uma boa ideia criar uma seção onde só são adicionados materiais com legendas e são em inglês e manter o currículo principal somente em PT-BR.

**Comment by Camilotk** [comment]
Atualmente o "Sim" para inclusão de materiais legendados está ganhando de 10:1.

Caso isso aconteça até o fim da votação o que pretendo é ainda dar preferência por materiais do Brasil, mas vou começar por adicionar Cursos legendados em PT-Br do Coursera nas trilhas de Ciência de Dados (que será criada) e Computação Gráfica (que será incrementada).

**Comment by yanbrasiliano** [comment]
Acredito que deva se manter o conteúdo em inglês, mas com o aporte de legendas. É bom também sempre manter a alternativa de cursos em PT-BR e indicação do curso em inglês-legendado.

Uma dica é disponibilizar conteúdo para aprendizado da língua inglesa também, apesar de não ser o foco.

**Comment by Camilotk** [comment]
@yanbrasiliano os cursos legendados você mais como conteúdo extra ou principal?

Sobre Inglês: Tem a cadeira de Inglês técnico que traz o básico do idioma, mas para além disso podemos pensar futuramente em um currículo separado para aprendizagem de Inglês. 

> No momento ainda tem muita coisa por fazer em CC e vou tentar focar em deixar esse currículo redondinho primeiro, mas se alguém quiser o B.O. de criar currículos de outros cursos e treinamentos eu apoio como puder (tenho interesse nisso), é só mandar email para [camilotk@gmail.com](#) com a proposta que vamos conversando.

**Comment by yanbrasiliano** [comment]
@Camilotk penso que, se estes forem de maior abrangência, entrariam como principal. Mas sempre é bom colocar uma alternativa PT-BR. Algo como: " Caso optem por um conteúdo nacional, segue sugestão: ..." .

**Comment by Camilotk** [comment]
Fechando a votação e concluindo a votação!

- ```50``` votos para **Sim**.
- `2` votos para **Não**. 

Além disso, materiais experimentais foram adicionados à grade por 2 semanas e não houve qualquer reclamação ou feedback negativo.

Por tanto, materiais legendados em PT-Br também serão adicionados a grade quando houver sentido nessa escolha, seja por conteúdo melhor ou diferenciado ou escassez de opções de qualidade sobre o tópico.

Obrigado a quem votou e participou da discussão! 
O feedback e opinião de vocês é muito importante para que continuemos a fazer os ajustes necessários para levar conteúdo de qualidade e de forma acessível a todos!
