### ISSUE TITLE
Tenho outra sugestão para quem quer fazer o acompanhamento dos estudos, que seria criar um repositório pessoal ex" UBL-roteiro-de-estudos" e dentro dele abrir uma issue com o seguinte conteúdo.

### ISSUE THREAD

**Issue by ValdineiJunior** [Universidade-Livre/ciencia-da-computacao#60]
Técnicas de estudo, organização e aprendizagem

- [ ] [Aprendendo a aprender](https://pt.coursera.org/learn/aprender)
- [ ] [Como estudar do jeito certo](https://www.youtube.com/playlist?list=PL5TJqBvpXQv7Q2lT7L7BrTrh6tgZY872s)

Git e GitHub

- [ ] [Git e Github para Iniciantes](https://www.youtube.com/playlist?list=PLlAbYrWSYTiPA2iEiQ2PF_A9j__C4hi0A)
- [ ] [Git e GitHub](https://www.cursoemvideo.com/curso/curso-de-git-e-github/)

Introdução à Computação

- [ ] [Introdução à Ciência da Computação com Python I](https://www.coursera.org/learn/ciencia-computacao-python-conceitos)
- [ ] [Fundamentos Matemáticos para Computação](https://www.youtube.com/watch?v=QE6ruiq632o&list=PLrOyM49ctTx-HWypJVvn_zMO1o7oOAfVx)
- [ ] [Ciência da Computação 50 (CC50)](https://materiais.estudarfora.org.br/cc50-harvard/)
- [ ] [Leitura e Produção de Textos](https://youtube.com/playlist?list=PLxI8Can9yAHemh_YJh9GtkIUljZbI7Tvw)
- [ ] [Circuitos Digitais](https://www.youtube.com/playlist?list=PLXyWBo_coJnMYO9Na3t-oYsc2X4kPJBWf)

Aprofundamento de Conceitos Introdutórios

- [ ] [Introdução à Ciência da Computação com Python II](https://pt.coursera.org/learn/ciencia-computacao-python-conceitos-2)
- [ ] [Estatística e Probabilidade](https://www.youtube.com/playlist?list=PLxI8Can9yAHeeWqe3m9HZFiBhT33Mfxew)
- [ ] [Arquitetura de Computadores I](https://www.youtube.com/playlist?list=PLEUHFTHcrJmswfeq7QEHskgkT6HER3gK6)
- [ ] [Noções de Inglês](https://www.youtube.com/playlist?list=PLxI8Can9yAHeYb4-3dXwiY2Z9VdqhnqpM)
- [ ] [Noções de Direitos Autorais, parte I](https://www.escolavirtual.gov.br/curso/72)
- [ ] [Noções de Direitos Autorais, parte II](https://www.youtube.com/playlist?list=PLxI8Can9yAHcoBrn53XO581IsIXHqgShZ)

Desenvolvimento Técnico

- [ ] [Programação Orientada a Objetos I](https://pt.coursera.org/learn/lab-poo-parte-1)
- [ ] [Bancos de Dados](https://cursos.univesp.br/courses/3129)
- [ ] [Arquitetura de Computadores II](https://www.youtube.com/playlist?list=PLEUHFTHcrJmsqKX-GDD-hBvkF8h2_BfKJ)
- [ ] [Algebra Linear I](https://www.youtube.com/playlist?list=PLIEzh1OveCVczEZAjhVIVd7Qs-X8ILgnI)
- [ ] [Princípios de Desenvolvimento Ágil de Software](https://pt.coursera.org/learn/principios-de-desenvolvimento-agil-de-software)

Desenvolvimento Teórico

- [ ] [Desenvolvimento Ágil com Java Avançado](https://pt.coursera.org/learn/desenvolvimento-agil-com-java-avancado)
- [ ] [Cálculo I](https://www.youtube.com/playlist?list=PLxI8Can9yAHd2Tjqa68gx_2R5YOkzOLgS)
- [ ] [Teoria dos Grafos](https://www.youtube.com/playlist?list=PLndfcZyvAqbr2MLCOLEvBNX6FgD8UNWfX)
- [ ] [Sistemas Operacionais](http://wiki.inf.ufpr.br/maziero/doku.php?id=socm:start)
- [ ] [Banco de Dados MySQL](https://www.youtube.com/playlist?list=PLucm8g_ezqNrWAQH2B_0AnrFY5dJcgOLR)

Aprofundamento Técnico

- [ ] [Interfaces Humano-Computador](https://www.youtube.com/playlist?list=PLxI8Can9yAHcoiFzGoyLITBKzFbiw3RIp)
- [ ] [Estrutura de Dados](https://www.youtube.com/playlist?list=PLUukMN0DTKCtdKaIUQoV4VWqGblYGZLfC)
- [ ] [Redes de Computadores](https://www.youtube.com/playlist?list=PLxI8Can9yAHc-_dZ6nsfoon08i2-4OvEk)
- [ ] [Criação de Startups](https://pt.coursera.org/learn/criacao-startups)
- [ ] [Introdução ao Desenvolvimento de Aplicativos Android](https://pt.coursera.org/learn/introducao-aplicativos-android)

Tópicos Finais

- [ ] [Paradigmas de Programação](https://www.youtube.com/playlist?list=PLYItvall0TqJ25sVTLcMhxsE0Hci58mpQ)
- [ ] [Exercícios de Paradigmas de Programação](https://www.youtube.com/playlist?list=PLYItvall0TqJU369ZZ2oNN9mrhLX6Myqk)
- [ ] [Compiladores](https://www.youtube.com/playlist?list=PLjcmNukBom6--0we1zrpoUE2GuRD-Me6W)
- [ ] [Gerência da Qualidade de Software](https://www.youtube.com/playlist?list=PLxI8Can9yAHcmjsfjFdo_xJ3xhLiczzLC)
- [ ] [Fundamentos da Inteligência Artificial](https://www.youtube.com/playlist?list=PLtQM10PgmGogjn0cikgWi8wpQUnV6ERkY)
- [ ] [Metodologia da Pesquisa em Computação](https://www.youtube.com/playlist?list=PLclUQno6PMpQO0-XrDwWsPzRzEvjwp1__)

Especializações

- [ ] [Computação Gráfica](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/computer_graphics.md)
- [ ] [Embarcados](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/embedded_systems.md)
- [ ] [Desenvolvimento Web](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/web_development.md)
- [ ] [Ciência de Dados](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/data_science.md)
- [ ] [CyberSecurity](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/cybersecurity.md)
- [ ] [DevOps](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/devops.md)

**Comment by jeffque** [comment]
Será que dá para fazer um repositório boilerplate com isso?

Quem sabe até estimulando um zettelstaken para armazenar notas como sendo o repositório pessoal?

**Comment by mateusrovedaa** [comment]
Bacana, da para pensarmos em ter um repo mesmo. Ou até mesmo a pessoa copiar e seguir.

**Comment by Mateus-Sebastian** [comment]
> Técnicas de estudo, organização e aprendizagem
> 
> * [ ]  [Aprendendo a aprender](https://pt.coursera.org/learn/aprender)
> * [ ]  [Como estudar do jeito certo](https://www.youtube.com/playlist?list=PL5TJqBvpXQv7Q2lT7L7BrTrh6tgZY872s)
> 
> Git e GitHub
> 
> * [ ]  [Git e Github para Iniciantes](https://www.youtube.com/playlist?list=PLlAbYrWSYTiPA2iEiQ2PF_A9j__C4hi0A)
> * [ ]  [Git e GitHub](https://www.cursoemvideo.com/curso/curso-de-git-e-github/)
> 
> Introdução à Computação
> 
> * [ ]  [Introdução à Ciência da Computação com Python I](https://www.coursera.org/learn/ciencia-computacao-python-conceitos)
> * [ ]  [Fundamentos Matemáticos para Computação](https://www.youtube.com/watch?v=QE6ruiq632o&list=PLrOyM49ctTx-HWypJVvn_zMO1o7oOAfVx)
> * [ ]  [Ciência da Computação 50 (CC50)](https://materiais.estudarfora.org.br/cc50-harvard/)
> * [ ]  [Leitura e Produção de Textos](https://youtube.com/playlist?list=PLxI8Can9yAHemh_YJh9GtkIUljZbI7Tvw)
> * [ ]  [Circuitos Digitais](https://www.youtube.com/playlist?list=PLXyWBo_coJnMYO9Na3t-oYsc2X4kPJBWf)
> 
> Aprofundamento de Conceitos Introdutórios
> 
> * [ ]  [Introdução à Ciência da Computação com Python II](https://pt.coursera.org/learn/ciencia-computacao-python-conceitos-2)
> * [ ]  [Estatística e Probabilidade](https://www.youtube.com/playlist?list=PLxI8Can9yAHeeWqe3m9HZFiBhT33Mfxew)
> * [ ]  [Arquitetura de Computadores I](https://www.youtube.com/playlist?list=PLEUHFTHcrJmswfeq7QEHskgkT6HER3gK6)
> * [ ]  [Noções de Inglês](https://www.youtube.com/playlist?list=PLxI8Can9yAHeYb4-3dXwiY2Z9VdqhnqpM)
> * [ ]  [Noções de Direitos Autorais, parte I](https://www.escolavirtual.gov.br/curso/72)
> * [ ]  [Noções de Direitos Autorais, parte II](https://www.youtube.com/playlist?list=PLxI8Can9yAHcoBrn53XO581IsIXHqgShZ)
> 
> Desenvolvimento Técnico
> 
> * [ ]  [Programação Orientada a Objetos I](https://pt.coursera.org/learn/lab-poo-parte-1)
> * [ ]  [Bancos de Dados](https://cursos.univesp.br/courses/3129)
> * [ ]  [Arquitetura de Computadores II](https://www.youtube.com/playlist?list=PLEUHFTHcrJmsqKX-GDD-hBvkF8h2_BfKJ)
> * [ ]  [Algebra Linear I](https://www.youtube.com/playlist?list=PLIEzh1OveCVczEZAjhVIVd7Qs-X8ILgnI)
> * [ ]  [Princípios de Desenvolvimento Ágil de Software](https://pt.coursera.org/learn/principios-de-desenvolvimento-agil-de-software)
> 
> Desenvolvimento Teórico
> 
> * [ ]  [Desenvolvimento Ágil com Java Avançado](https://pt.coursera.org/learn/desenvolvimento-agil-com-java-avancado)
> * [ ]  [Cálculo I](https://www.youtube.com/playlist?list=PLxI8Can9yAHd2Tjqa68gx_2R5YOkzOLgS)
> * [ ]  [Teoria dos Grafos](https://www.youtube.com/playlist?list=PLndfcZyvAqbr2MLCOLEvBNX6FgD8UNWfX)
> * [ ]  [Sistemas Operacionais](http://wiki.inf.ufpr.br/maziero/doku.php?id=socm:start)
> * [ ]  [Banco de Dados MySQL](https://www.youtube.com/playlist?list=PLucm8g_ezqNrWAQH2B_0AnrFY5dJcgOLR)
> 
> Aprofundamento Técnico
> 
> * [ ]  [Interfaces Humano-Computador](https://www.youtube.com/playlist?list=PLxI8Can9yAHcoiFzGoyLITBKzFbiw3RIp)
> * [ ]  [Estrutura de Dados](https://www.youtube.com/playlist?list=PLUukMN0DTKCtdKaIUQoV4VWqGblYGZLfC)
> * [ ]  [Redes de Computadores](https://www.youtube.com/playlist?list=PLxI8Can9yAHc-_dZ6nsfoon08i2-4OvEk)
> * [ ]  [Criação de Startups](https://pt.coursera.org/learn/criacao-startups)
> * [ ]  [Introdução ao Desenvolvimento de Aplicativos Android](https://pt.coursera.org/learn/introducao-aplicativos-android)
> 
> Tópicos Finais
> 
> * [ ]  [Paradigmas de Programação](https://www.youtube.com/playlist?list=PLYItvall0TqJ25sVTLcMhxsE0Hci58mpQ)
> * [ ]  [Exercícios de Paradigmas de Programação](https://www.youtube.com/playlist?list=PLYItvall0TqJU369ZZ2oNN9mrhLX6Myqk)
> * [ ]  [Compiladores](https://www.youtube.com/playlist?list=PLjcmNukBom6--0we1zrpoUE2GuRD-Me6W)
> * [ ]  [Gerência da Qualidade de Software](https://www.youtube.com/playlist?list=PLxI8Can9yAHcmjsfjFdo_xJ3xhLiczzLC)
> * [ ]  [Fundamentos da Inteligência Artificial](https://www.youtube.com/playlist?list=PLtQM10PgmGogjn0cikgWi8wpQUnV6ERkY)
> * [ ]  [Metodologia da Pesquisa em Computação](https://www.youtube.com/playlist?list=PLclUQno6PMpQO0-XrDwWsPzRzEvjwp1__)
> 
> Especializações
> 
> * [ ]  [Computação Gráfica](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/computer_graphics.md)
> * [ ]  [Embarcados](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/embedded_systems.md)
> * [ ]  [Desenvolvimento Web](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/web_development.md)
> * [ ]  [Ciência de Dados](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/data_science.md)
> * [ ]  [CyberSecurity](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/cybersecurity.md)
> * [ ]  [DevOps](https://github.com/Universidade-Livre/ciencia-da-computacao/blob/main/specializations/devops.md)
