### ISSUE TITLE
Link de disciplina mais completa sobre compiladores

### ISSUE THREAD

**Issue by diegogit03** [Universidade-Livre/ciencia-da-computacao#63]
Creio que está playlist está mais completa que a que está atualmente na grade:
https://www.youtube.com/playlist?list=PLX6Nyaq0ebfhI396WlWN6WlBm-tp7vDtV

**Comment by mateusrovedaa** [comment]
Temos que avaliar apenas se faz sentido trocar (não assisti as aulas). Vou anotar para fazer isso.

**Comment by mateusrovedaa** [comment]
Fechando em virtude da PR #85. Caso ainda for interessante a alteração, favor abrir uma nova issue.
