### ISSUE TITLE
Criação de um Notion para acompanhamento

### ISSUE THREAD

**Issue by jacksonsilvafilho** [Universidade-Livre/ciencia-da-computacao#79]
Prezados, sugiro a criação de um Notion para acompanhamento pessoal do desenvolvimento de cada estudante.

**Comment by elvcastelo** [comment]
Como funcionaria isso? Seria para marcar as disciplinas concluídas?

**Comment by mateusrovedaa** [comment]
Por falta de respostas, estou fechando a issue.
