### ISSUE TITLE
Links para os livros

### ISSUE THREAD

**Issue by hamadecd** [Universidade-Livre/ciencia-da-computacao#83]
Vou listar aqui os livros que estão direcionando para o livro errado ao qual se refere e o link correto.

- Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos. [link correto](https://www.amazon.com.br/Entendendo-Algoritmos-Ilustrado-Programadores-Curiosos/dp/8575225634)
- Algoritmos - Teoria e Prática. [link correto](https://www.amazon.com.br/Algoritmos-Teoria-Pr%C3%A1tica-Thomas-Cormen/dp/8535236996/)
- Grafos: Teoria, Modelos, Algoritmos. [link correto](https://www.amazon.com.br/Grafos-Paulo-Oswaldo-Boaventura-Netto/dp/8521206801)
- Problemas Clássicos de Ciência da Computação com Python. [link correto](https://www.amazon.com.br/Problemas-Cl%C3%A1ssicos-Ci%C3%AAncia-Computa%C3%A7%C3%A3o-Python/dp/8575228056)

**Comment by mateusrovedaa** [comment]
Fechando em virtude da PR #85.
